#===========================
# Playback
#===========================

hr-seek=yes

ENTER cycle fullscreen
KP_Enter cycle fullscreen

RIGHT				seek	 2 exact
LEFT 				seek 	-2 exact
Ctrl+RIGHT 	seek  10 exact
Ctrl+LEFT 	seek -10 exact

+	add		speed 	 0.1
-	add 	speed 	-0.1

l cycle_values loop-file inf no

A cycle-values video-aspect "16:9" "9:16" "4:3" "3:4" "2.35:1" "1:2.35" "-1"
r cycle_values video-rotate 90 180 270 0

#===========================
# Volume
#===========================

UP			add volume  5
DOWN		add volume -5

AXIS_UP 	add volume 	5
AXIS_DOWN   add volume -5

#===========================
# Subtitles
#===========================

#Ctrl++	add sub-font-size	 1
#Ctrl+-	add sub-font-size -1
