#! /bin/sh
pkill polybar
polybar example &
pkill dunst
dunst &
setxkbmap -layout "us,latam" -option "grp:alt_shift_toggle" &
~/.fehbg &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width          2
bspc config window_gap            12
bspc config top_padding 	        20
bspc config bottom_padding 	      0
#bspc config border_width 	      0
#bspc config window_gap           0 
#bspc config top_padding 	        0

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config normal_border_color 	  "#262B32"
bspc config focused_border_color 	  "#70BCF1"
bspc config presel_feedback_color 	"#D08FE2"

bspc rule -a Zathura		    state=tiled
bspc rule -a firefox 		    desktop='^1'
bspc rule -a Chromium 		  desktop='^5'
bspc rule -a spotify        desktop='^9'
bspc rule -a Spotify        desktop='^9'
bspc rule -a qBittorrent 		desktop='^10'
