#! /bin/bash
# ================================
#             Startup            |
# ============ M.B.G. ============

xsetroot -cursor_name left_ptr &
setxkbmap -layout "us,latam" -option "grp:alt_shift_toggle" &

numlockx &
pkill sxhkd
# pkill dunst
# pkill wallchange
# pkill archupdate
# pkill polybar

pgrep -x dunst >/dev/null || dunst &
pgrep -x sxhkd >/dev/null || sxhkd &
pgrep -x picom >/dev/null || picom -b &
pgrep -x wallchange >/dev/null || wallchange &
pgrep -x archupdate >/dev/null || archupdate &
pgrep -x polybar >/dev/null || polybar mybar &

#==============================
#     BSPWM Settings          |
#==============================

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

# Normal window mode
bspc config border_width 2
bspc config window_gap 0
bspc config top_padding 21

# bspc config border_width 0
# bspc config window_gap 0
# bspc config top_padding 0

# Window options
bspc config split_ratio 0.5
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config focus_follows_pointer false

#==============================
#        BSPC Rules           |
#==============================
# Desktop rules
bspc rule -a firefox desktop='^1'
bspc rule -a firefoxdeveloperedition desktop='^5'
bspc rule -a Brave-browser desktop='^5'
bspc rule -a Spotify desktop='^8'
bspc rule -a qBittorrent desktop='^10'

# Tiling rules
bspc rule -a Zathura state=tiled
bspc rule -a firefox state=tiled

#==============================
#        Colorscheme          |
#==============================

# Tokyonight
bspc config focused_border_color "#7aa2f7"
bspc config normal_border_color "#24283b"
bspc config active_border_color "#f7768e"

# =============================
# PavuControl                 |
# =============================
pulseaudio --check
pulseaudio -D

wmname LG3D
